services:
  # PHP service with Symfony
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - postgre
    environment:
      DATABASE_URL: "postgresql://postgre_user:postgre_pass@postgre:5432/postgre_dev?serverVersion=15&charset=utf8"

  # Nginx service
  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PostgreSQL service
  postgre:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgre_user
      POSTGRES_PASSWORD: postgre_pass
      POSTGRES_DB: postgre_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgre_data:
