services:
  # PHP service with Symfony
  php:
    build:
      dockerfile: .docker/php/Dockerfile
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./symfony:/app/public
      - caddy_data:/data
      - caddy_config:/config
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true
    depends_on:
      - postgre

  # PostgreSQL service
  postgre:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgre_user
      POSTGRES_PASSWORD: postgre_pass
      POSTGRES_DB: postgre_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgre_data:
  caddy_data:
  caddy_config:
