version: '3.8'

services:
  # PHP service with Symfony
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@postgres:5432/symfony?serverVersion=15&charset=utf8"
    # Override for development to use the development PHP ini
    command: sh -c "mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini && php-fpm"
    user: "1000:1000" # Use your host user ID for permissions (adjust as needed)

  # Nginx service with fixed version
  nginx:
    image: nginx:1.25.3
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PostgreSQL service with fixed version
  postgres:
    image: postgres:15.4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: symfony
      POSTGRES_USER: symfony
      POSTGRES_DB: symfony
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: