services:
  # PHP service with Symfony
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://app:app@database:5432/app?serverVersion=15&charset=utf8"

  # Nginx service
  web:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PostgreSQL service
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database_data:
